export const RESTAURANTS=[{name:"Bollywood Spice",   city:"Bienne",      address:"Rue de la gare", style:"Indian", rating:1, image:"/images/indian.jpg" ,place:5},
                          {name:"Spice Up",          city:"Saint-Imier", address:"Rue des prés", style:"Indian", rating:2, image:"/images/indian.jpg",place:0},
                          {name:"Salad Story",       city:"Genève",      address:"Rue de la gare", style:"Indian", rating:5, image:"/images/indian.jpg",place:2},
                          {name:"Indian Vegan Heat", city:"Genève",      address:"Rue de la gare", style:"Indian", rating:4, image:"/images/indian.jpg",place:4},
                          {name:"Taj Mehal",         city:"Lausanne",    address:"Rue des prés", style:"Indian", rating:0, image:"/images/indian.jpg",place:0},
                          {name:"Indian Express",    city:"Bienne",      address:"Rue des prés", style:"Indian", rating:1, image:"/images/indian.jpg",place:10},
                          {name:"Indian Masala",     city:"Saint-Imier", address:"Rue de la gare", style:"Indian", rating:4, image:"/images/indian.jpg",place:12},
                          {name:"Roti Mojo",         city:"Neuchâtel",   address:"Rue de la paix", style:"Indian", rating:4, image:"/images/indian.jpg",place:5},
                          {name:"Dosalon Chai",      city:"Lausanne",    address:"Rue de la paix", style:"Indian", rating:2, image:"/images/indian.jpg",place:5},
                          {name:"Lai Lounge",        city:"Neuchâtel",   address:"Rue de la gare", style:"Indian", rating:1, image:"/images/indian.jpg",place:0},
                          {name:"Spirit of Chai",    city:"Neuchâtel",   address:"Rue des prés", style:"Indian", rating:2, image:"/images/indian.jpg",place:15},
                          {name:"Oregano's",              city:"Saint-Imier", address:"Rue de la gare", style:"Italian", rating:4, image:"/images/italian.jpg",place:4},
                          {name:"Bella Bella Mozzarella", city:"Neuchâtel",   address:"Rue des prés", style:"Italian", rating:2, image:"/images/italian.jpg",place:1},
                          {name:"The Spicey Meatball",    city:"Lausanne",    address:"Rue de la gare", style:"Italian", rating:4, image:"/images/italian.jpg",place:0},
                          {name:"Eatie Some Ziti",        city:"Bienne",      address:"Rue de la paix", style:"Italian", rating:1, image:"/images/italian.jpg",place:0},
                          {name:"Scamp's Scampi",         city:"Neuchâtel",   address:"Rue de la paix", style:"Italian", rating:0, image:"/images/italian.jpg",place:8}
]
