export const RESTAURANTS=[{id:0,name:"Bollywood Spice",   city:"Bienne",      address:"Rue de la gare", style:"Indian", rating:1, image:"/images/indian.jpg" ,place:5, lat:47.138350, lng:7.246494},
                          {id:1,name:"Spice Up",          city:"Saint-Imier", address:"Rue des prés", style:"Indian", rating:2, image:"/images/indian.jpg",place:0, lat:47.153101, lng:6.997596},
                          {id:2,name:"Salad Story",       city:"Genève",      address:"Rue de la gare", style:"Indian", rating:5, image:"/images/indian.jpg",place:2, lat:46.210151, lng:6.138734},
                          {id:3,name:"Indian Vegan Heat", city:"Genève",      address:"Rue de la gare", style:"Indian", rating:4, image:"/images/indian.jpg",place:4, lat:46.202051, lng:6.141430},
                          {id:4,name:"Taj Mehal",         city:"Lausanne",    address:"Rue des prés", style:"Indian", rating:0, image:"/images/indian.jpg",place:0, lat:46.520150, lng:6.633774},
                          {id:5,name:"Indian Express",    city:"Bienne",      address:"Rue des prés", style:"Indian", rating:1, image:"/images/indian.jpg",place:1, lat:47.138350, lng:7.246494},
                          {id:6,name:"Indian Masala",     city:"Saint-Imier", address:"Rue de la gare", style:"Indian", rating:4, image:"/images/indian.jpg",place:12, lat:47.138350, lng:7.246494},
                          {id:7,name:"Roti Mojo",         city:"Neuchâtel",   address:"Rue de la paix", style:"Indian", rating:4, image:"/images/indian.jpg",place:5, lat:47.138350, lng:7.246494},
                          {id:8,name:"Dosalon Chai",      city:"Lausanne",    address:"Rue de la paix", style:"Indian", rating:2, image:"/images/indian.jpg",place:5,lat:46.520150, lng:6.633774},
                          {id:9,name:"Lai Lounge",        city:"Neuchâtel",   address:"Rue de la gare", style:"Indian", rating:1, image:"/images/indian.jpg",place:0, lat:47.138350, lng:7.246494},
                          {id:10,name:"Spirit of Chai",    city:"Neuchâtel",   address:"Rue des prés", style:"Indian", rating:2, image:"/images/indian.jpg",place:15, lat:47.138350, lng:7.246494},
                          {id:11,name:"Oregano's",              city:"Saint-Imier", address:"Rue de la gare", style:"Italian", rating:4, image:"/images/italian.jpg",place:4, lat:47.138350, lng:7.246494},
                          {id:12,name:"Bella Bella Mozzarella", city:"Neuchâtel",   address:"Rue des prés", style:"Italian", rating:2, image:"/images/italian.jpg",place:1, lat:47.138350, lng:7.246494},
                          {id:13,name:"The Spicey Meatball",    city:"Lausanne",    address:"Rue de la gare", style:"Italian", rating:4, image:"/images/italian.jpg",place:0, lat:47.138350, lng:7.246494},
                          {id:14,name:"Eatie Some Ziti",        city:"Bienne",      address:"Rue de la paix", style:"Italian", rating:1, image:"/images/italian.jpg",place:0, lat:47.138350, lng:7.246494},
                          {id:15,name:"Scamp's Scampi",         city:"Neuchâtel",   address:"Rue de la paix", style:"Italian", rating:0, image:"/images/italian.jpg",place:8, lat:47.138350, lng:7.246494}
]
